-- Migration: retailer_staff_invitation_storage_foundation
-- Purpose: The storage + authorization-root foundation for Retailer staff
--          invitations. It adds, and only adds:
--            1. public.retailer_staff_invitations — the pending/settled invitation
--               record for a RETAILER_MANAGER or SALES_STAFF invitee, driven by a
--               single application-owned token flow that serves both new and
--               existing Auth accounts.
--            2. public.retailer_invitation_shop_assignments — the immutable set of
--               intended shops preserved while a SALES_STAFF invitation is pending,
--               applied atomically on acceptance by a future RPC.
--            3. public.resolve_retailer_member_organization(text) — the internal,
--               read-only authorization resolver every future staff RPC will call.
--          Plus the validation/immutability triggers, indexes, and default-deny
--          RLS + privilege hardening for the two tables.
--
-- WHY A SEPARATE TABLE FROM public.retailer_invitations
--   The Retailer Owner invitation domain (migrations 15/19/20) is owner-specific
--   and single-owner-specific: get_vendor_retailer_owner_status reads the newest
--   PENDING row for a retailer WITHOUT a role filter, and a GLOBAL unique index
--   (retailer_invitations_auth_user_pending_idx) permits only one pending
--   invitation per Auth user. Staff need the opposite: many staff per retailer, and
--   the same person invited to different retailers. Keeping staff invitations in
--   their own table leaves every owner object BYTE-IDENTICAL, and lets the staff
--   indexes express multi-staff/multi-retailer natively. This migration therefore
--   does NOT touch retailer_invitations, any owner/portal function,
--   retailer_shop_members, roles/permissions, or any existing policy.
--
-- ONE APPLICATION-OWNED TOKEN FLOW (both new and existing accounts)
--   Only SHA-256(raw token) is ever stored (token_hash, 64 lowercase hex), only on
--   a live PENDING invitation, and retained across a delivery failure. The raw
--   token is generated by the server, may appear in the recipient's URL, and is
--   never stored, logged, or audited. There is deliberately NO invitation_kind: the
--   acceptance RPC (a later migration) determines new-vs-existing from the real
--   auth/profile state, never a stored flag. There is NO vendor_organization_id:
--   staff invitations are retailer-internal, issued by the Retailer Owner.
--
-- WHAT THIS MIGRATION DELIBERATELY DOES NOT DO
--   No reserve/resend/revoke/delivery/recipient/acceptance RPC; no
--   expire_stale_retailer_staff_invitations(); no audit-log write; no feature flag;
--   no route/Server Action/email template. Storage + authorization root only.
--   Access to both tables exists solely through future SECURITY DEFINER RPCs.
--
-- Idempotency posture: plain CREATE (no IF NOT EXISTS, no CREATE OR REPLACE). A
--   conflicting existing object FAILS the migration rather than being silently
--   accepted, matching the repository's schema-migration convention. No fixed
--   UUIDs anywhere.
--
-- Dependencies: 20260716124419 (organizations, profiles, organization_members,
--   set_updated_at), 20260716125559 (roles, permissions, role_permissions,
--   member_roles), 20260717094520 (retailer_shops, assert_organization_type),
--   20260722210000 (RETAILER_MANAGER, SALES_STAFF, RETAILER_STAFF_* permissions and
--   their mappings — the resolver and role trigger rely on these).

-- ============================================================================
-- SECTION 1 — public.retailer_staff_invitations (table + FKs + 18 checks)
-- ============================================================================
create table public.retailer_staff_invitations (
  id                       uuid        primary key default gen_random_uuid(),

  -- The retailer the staff member joins. RESTRICT: retailers retire by status,
  -- never hard-deleted.
  retailer_organization_id uuid        not null,

  -- Stored ALREADY canonical (trimmed + lower-cased); enforced by the check below.
  email                    text        not null,

  -- The invitee's real name, collected from the inviting owner. Never invented.
  first_name               text        not null,
  last_name                text        not null,

  -- The target role. A trigger restricts this to an ACTIVE RETAILER_MANAGER or
  -- SALES_STAFF role; RESTRICT follows member_roles.role_id.
  role_id                  uuid        not null,

  status                   text        not null default 'PENDING',

  -- Set only at acceptance (token flow → NULL while PENDING). SET NULL so removing
  -- the Auth user preserves accepted history (see the context checks below).
  auth_user_id             uuid        null,

  -- Set at acceptance to the produced membership. SET NULL for the same reason.
  organization_member_id   uuid        null,

  -- Who issued it. SET NULL follows member_roles.assigned_by.
  invited_by_profile_id    uuid        null,

  -- SHA-256(raw token) as 64 lowercase hex; only on a live PENDING invitation;
  -- retained across a delivery failure; cleared on accept/revoke/expire.
  token_hash               text        null,

  -- The only staff failure code this milestone recognises.
  failure_code             text        null,
  failure_recorded_at      timestamptz null,

  expires_at               timestamptz not null default (now() + interval '24 hours'),
  sent_at                  timestamptz null,
  accepted_at              timestamptz null,
  revoked_at               timestamptz null,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),

  -- Foreign keys (explicit, stable names) --------------------------------------
  constraint retailer_staff_invitations_retailer_fk
    foreign key (retailer_organization_id)
    references public.organizations (id) on delete restrict,
  constraint retailer_staff_invitations_role_fk
    foreign key (role_id)
    references public.roles (id) on delete restrict,
  constraint retailer_staff_invitations_auth_user_fk
    foreign key (auth_user_id)
    references auth.users (id) on delete set null,
  constraint retailer_staff_invitations_member_fk
    foreign key (organization_member_id)
    references public.organization_members (id) on delete set null,
  constraint retailer_staff_invitations_invited_by_fk
    foreign key (invited_by_profile_id)
    references public.profiles (id) on delete set null,

  -- 18 check constraints --------------------------------------------------------
  -- 1. Canonical email, enforced by the database rather than trusted of callers.
  constraint retailer_staff_invitations_email_canonical
    check (
      email = lower(btrim(email))
      and length(email) > 0
      and length(email) <= 254
    ),
  -- 2. Pragmatic shape check. COLLATE "C" is load-bearing (locale-independent
  --    bracket ranges), matching retailer_invitations_email_shape.
  constraint retailer_staff_invitations_email_shape
    check (email collate "C" ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  -- 3/4. Names non-empty after trimming.
  constraint retailer_staff_invitations_first_name_not_empty
    check (length(btrim(first_name)) > 0),
  constraint retailer_staff_invitations_last_name_not_empty
    check (length(btrim(last_name)) > 0),
  -- 5. Names stored already trimmed.
  constraint retailer_staff_invitations_names_trimmed
    check (first_name = btrim(first_name) and last_name = btrim(last_name)),
  -- 6. Stored lifecycle statuses.
  constraint retailer_staff_invitations_status_allowed
    check (status in ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED')),
  -- 7/8. Status and its timestamp move together (strict equivalence — these
  --      timestamps are not FK columns and never get SET NULL).
  constraint retailer_staff_invitations_accepted_consistent
    check ((status = 'ACCEPTED') = (accepted_at is not null)),
  constraint retailer_staff_invitations_revoked_consistent
    check ((status = 'REVOKED') = (revoked_at is not null)),
  -- 9/10. CONTEXT constraints (one-directional): an acceptance reference may exist
  --       ONLY on an ACCEPTED row, so PENDING/REVOKED/EXPIRED can never carry one.
  --       Written as `ref IS NULL OR status = 'ACCEPTED'` so a later ON DELETE SET
  --       NULL on an accepted history row (which clears the ref while status stays
  --       ACCEPTED) still satisfies the rule and the FK action succeeds.
  --       Transition-time completeness ("both refs required when becoming
  --       ACCEPTED") is enforced by the acceptance-references trigger, not here.
  constraint retailer_staff_invitations_auth_user_context
    check (auth_user_id is null or status = 'ACCEPTED'),
  constraint retailer_staff_invitations_member_context
    check (organization_member_id is null or status = 'ACCEPTED'),
  -- 11. Token hash shape.
  constraint retailer_staff_invitations_token_hash_format
    check (token_hash is null or token_hash collate "C" ~ '^[0-9a-f]{64}$'),
  -- 12. A token may exist only on a live PENDING invitation.
  constraint retailer_staff_invitations_token_hash_context
    check (token_hash is null or status = 'PENDING'),
  -- 13. The only recognised staff failure code.
  constraint retailer_staff_invitations_failure_code_allowed
    check (failure_code is null or failure_code = 'EMAIL_DISPATCH_FAILED'),
  -- 14. Code and its timestamp move together.
  constraint retailer_staff_invitations_failure_consistent
    check ((failure_code is null) = (failure_recorded_at is null)),
  -- 15. A failure may exist only while PENDING (terminal states carry none).
  constraint retailer_staff_invitations_failure_context
    check (failure_code is null or status = 'PENDING'),
  -- 16. Never simultaneously "sent" and "failed".
  constraint retailer_staff_invitations_sent_or_failure
    check (not (sent_at is not null and failure_code is not null)),
  -- 17. A PENDING invitation that was sent must carry its token (scoped to PENDING
  --     so an ACCEPTED row whose token is cleared but whose sent_at persists as
  --     history is unaffected).
  constraint retailer_staff_invitations_pending_sent_has_token
    check (status <> 'PENDING' or sent_at is null or token_hash is not null),
  -- 18. A failure can only exist while the token is present (DELIVERY_FAILED
  --     retains its token for in-app recovery / resend rotation).
  constraint retailer_staff_invitations_failure_requires_token
    check (failure_code is null or token_hash is not null)
);

-- ============================================================================
-- SECTION 2 — Target-role validation (INSERT only; role_id is immutable)
-- ============================================================================
-- Guarantees role_id resolves to an ACTIVE role whose code is exactly
-- RETAILER_MANAGER or SALES_STAFF. A CHECK constraint cannot join roles, so this is
-- a trigger. SECURITY DEFINER + search_path='' so it reads public.roles as its
-- owner regardless of the writer's RLS. No dynamic SQL.
create function public.retailer_staff_invitations_assert_target_role()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_code   text;
  v_status text;
begin
  select r.code, r.status
    into v_code, v_status
  from public.roles r
  where r.id = new.role_id;

  -- BEFORE-row runs before the FK is checked, so a non-existent role can reach here.
  if v_code is null then
    raise exception 'Referenced role does not exist'
      using errcode = 'foreign_key_violation';
  end if;

  -- Rejects RETAILER_OWNER and every Vendor role (absent from the allow-set), and
  -- any inactive role. The message names the rule, never the role.
  if v_status <> 'ACTIVE' or v_code not in ('RETAILER_MANAGER', 'SALES_STAFF') then
    raise exception 'Staff invitation role must be an active Retailer Manager or Sales Staff role'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

revoke all     on function public.retailer_staff_invitations_assert_target_role() from public;
revoke execute on function public.retailer_staff_invitations_assert_target_role() from anon;
revoke execute on function public.retailer_staff_invitations_assert_target_role() from authenticated;

create trigger retailer_staff_invitations_assert_target_role_on_insert
  before insert on public.retailer_staff_invitations
  for each row execute function public.retailer_staff_invitations_assert_target_role();

-- ============================================================================
-- SECTION 3 — Retailer-type validation (INSERT only; retailer id is immutable)
-- ============================================================================
-- Reuses public.assert_organization_type() (migration 8) so all three tables that
-- carry this invariant enforce it with identical code. Type-only: a SUSPENDED
-- retailer is still a RETAILER; lifecycle belongs in future RPC authorization.
create function public.retailer_staff_invitations_assert_retailer_type()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.assert_organization_type(new.retailer_organization_id, 'RETAILER');
  return new;
end;
$$;

revoke all     on function public.retailer_staff_invitations_assert_retailer_type() from public;
revoke execute on function public.retailer_staff_invitations_assert_retailer_type() from anon;
revoke execute on function public.retailer_staff_invitations_assert_retailer_type() from authenticated;

create trigger retailer_staff_invitations_assert_retailer_type_on_insert
  before insert on public.retailer_staff_invitations
  for each row execute function public.retailer_staff_invitations_assert_retailer_type();

-- ============================================================================
-- SECTION 4 — Immutable invitation identity
-- ============================================================================
-- Once inserted, the retailer, recipient email, and target role are fixed. Changing
-- any of them is a different invitation and must go through revoke + replacement.
-- Names, lifecycle timestamps, token_hash, failure fields, status, auth_user_id and
-- organization_member_id remain updatable by future controlled RPCs.
create function public.retailer_staff_invitations_assert_immutable_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.retailer_organization_id is distinct from old.retailer_organization_id then
    raise exception 'Staff invitation Retailer is immutable; revoke and re-issue to change it'
      using errcode = 'check_violation';
  end if;
  if new.email is distinct from old.email then
    raise exception 'Staff invitation recipient email is immutable; revoke and re-issue to change it'
      using errcode = 'check_violation';
  end if;
  if new.role_id is distinct from old.role_id then
    raise exception 'Staff invitation role is immutable; revoke and re-issue to change it'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

revoke all     on function public.retailer_staff_invitations_assert_immutable_identity() from public;
revoke execute on function public.retailer_staff_invitations_assert_immutable_identity() from anon;
revoke execute on function public.retailer_staff_invitations_assert_immutable_identity() from authenticated;

-- UPDATE OF narrows firing to statements touching one of the three columns; the
-- WHEN clause narrows further to statements that actually change one. Fires
-- alphabetically before the other BEFORE-UPDATE triggers, so a forbidden change is
-- rejected first.
create trigger retailer_staff_invitations_assert_immutable_identity_on_update
  before update of retailer_organization_id, email, role_id
  on public.retailer_staff_invitations
  for each row
  when (
    new.retailer_organization_id is distinct from old.retailer_organization_id
    or new.email is distinct from old.email
    or new.role_id is distinct from old.role_id
  )
  execute function public.retailer_staff_invitations_assert_immutable_identity();

-- ============================================================================
-- SECTION 5 — Acceptance-reference validation
-- ============================================================================
-- Transition-time completeness: a row that BECOMES ACCEPTED must record both its
-- Auth user and its membership. Deliberately does NOT fire when an already-ACCEPTED
-- historical row later has either reference cleared by ON DELETE SET NULL (status
-- stays ACCEPTED, so neither WHEN clause matches) — that is how accepted history
-- survives Auth-user or membership deletion. The context checks (9/10) allow the
-- cleared state; this trigger only guards the transition INTO ACCEPTED.
create function public.retailer_staff_invitations_assert_acceptance_references()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.auth_user_id is null or new.organization_member_id is null then
    raise exception 'An accepted staff invitation must record both its Auth user and its membership'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

revoke all     on function public.retailer_staff_invitations_assert_acceptance_references() from public;
revoke execute on function public.retailer_staff_invitations_assert_acceptance_references() from anon;
revoke execute on function public.retailer_staff_invitations_assert_acceptance_references() from authenticated;

create trigger retailer_staff_invitations_assert_acceptance_refs_on_insert
  before insert on public.retailer_staff_invitations
  for each row
  when (new.status = 'ACCEPTED')
  execute function public.retailer_staff_invitations_assert_acceptance_references();

create trigger retailer_staff_invitations_assert_acceptance_refs_on_update
  before update of status
  on public.retailer_staff_invitations
  for each row
  when (new.status = 'ACCEPTED' and old.status is distinct from 'ACCEPTED')
  execute function public.retailer_staff_invitations_assert_acceptance_references();

-- ============================================================================
-- SECTION 6 — updated_at trigger (reuses public.set_updated_at())
-- ============================================================================
create trigger set_updated_at_on_retailer_staff_invitations
  before update on public.retailer_staff_invitations
  for each row execute function public.set_updated_at();

-- ============================================================================
-- SECTION 7 — Parent indexes (6 explicit; 7 total including the PK)
-- ============================================================================
-- THE duplicate guard: one live invitation per (retailer, canonical email).
-- Partial so any number of settled rows for that pair coexist. This is scoped to
-- the retailer, so the SAME email may hold a PENDING invitation in a DIFFERENT
-- retailer simultaneously — which is exactly why there is deliberately NO globally
-- unique auth-user pending index here (that owner-only rule lives on the owner
-- table and must not constrain staff who may serve multiple retailers).
create unique index retailer_staff_invitations_pending_unique_idx
  on public.retailer_staff_invitations (retailer_organization_id, email)
  where status = 'PENDING';

-- One live token per hash.
create unique index retailer_staff_invitations_token_hash_unique_idx
  on public.retailer_staff_invitations (token_hash)
  where token_hash is not null;

-- The roster question: "which staff invitations does this retailer have, in what
-- state?", newest first.
create index retailer_staff_invitations_retailer_status_created_idx
  on public.retailer_staff_invitations (retailer_organization_id, status, created_at desc);

-- The expiry sweep (used by a future RPC). Partial to the rows a sweep can act on.
create index retailer_staff_invitations_pending_expiry_idx
  on public.retailer_staff_invitations (expires_at)
  where status = 'PENDING';

-- Cross-retailer email lookup.
create index retailer_staff_invitations_email_idx
  on public.retailer_staff_invitations (email);

-- Acceptance-history lookup by Auth user (non-unique; a person may have accepted
-- invitations in several retailers).
create index retailer_staff_invitations_auth_user_idx
  on public.retailer_staff_invitations (auth_user_id)
  where auth_user_id is not null;

-- ============================================================================
-- SECTION 8 — Parent RLS and privilege hardening
-- ============================================================================
-- RLS enabled with ZERO policies: default-deny for anon and authenticated, reads
-- and writes alike. The browser reaches this table only through future SECURITY
-- DEFINER RPCs. postgres and service_role are untouched (they hold privileges
-- directly and service_role has BYPASSRLS).
alter table public.retailer_staff_invitations enable row level security;

revoke all on table public.retailer_staff_invitations from public;
revoke all on table public.retailer_staff_invitations from anon;
revoke all on table public.retailer_staff_invitations from authenticated;

-- ============================================================================
-- SECTION 9 — public.retailer_invitation_shop_assignments (table + FKs + unique)
-- ============================================================================
-- The immutable set of intended shops for a SALES_STAFF invitation, applied to
-- retailer_shop_members atomically on acceptance by a future RPC. No removed_at (an
-- immutable intended set), no updated_at (never updated), no assigned_by (the
-- parent's invited_by_profile_id records the actor), no status.
create table public.retailer_invitation_shop_assignments (
  id                            uuid        primary key default gen_random_uuid(),

  -- CASCADE: an intended-shop row has no meaning without its invitation, mirroring
  -- member_roles.organization_member_id and retailer_shop_members.
  retailer_staff_invitation_id  uuid        not null,

  -- RESTRICT: shops retire by status, never hard-deleted; a shop referenced by an
  -- invitation cannot be erased.
  retailer_shop_id              uuid        not null,

  created_at                    timestamptz not null default now(),

  constraint retailer_invitation_shop_assignments_invitation_fk
    foreign key (retailer_staff_invitation_id)
    references public.retailer_staff_invitations (id) on delete cascade,
  constraint retailer_invitation_shop_assignments_shop_fk
    foreign key (retailer_shop_id)
    references public.retailer_shops (id) on delete restrict,

  constraint retailer_invitation_shop_assignments_unique
    unique (retailer_staff_invitation_id, retailer_shop_id)
);

-- ============================================================================
-- SECTION 10 — Shop-assignment INSERT validation
-- ============================================================================
-- Defense in depth over the future reserve RPC: the shop must belong to the
-- invitation's own retailer, and only SALES_STAFF invitations may carry shop rows
-- (RETAILER_MANAGER explicitly rejected). Does NOT enforce the "at least one shop"
-- rule (a multi-row invariant that belongs to the reserve RPC).
create function public.retailer_invitation_shop_assignments_assert_valid()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_inv_retailer  uuid;
  v_role_id       uuid;
  v_role_code     text;
  v_shop_retailer uuid;
begin
  select i.retailer_organization_id, i.role_id
    into v_inv_retailer, v_role_id
  from public.retailer_staff_invitations i
  where i.id = new.retailer_staff_invitation_id;

  if v_inv_retailer is null then
    raise exception 'Referenced staff invitation does not exist'
      using errcode = 'foreign_key_violation';
  end if;

  select s.retailer_organization_id
    into v_shop_retailer
  from public.retailer_shops s
  where s.id = new.retailer_shop_id;

  if v_shop_retailer is null then
    raise exception 'Referenced shop does not exist'
      using errcode = 'foreign_key_violation';
  end if;

  if v_inv_retailer <> v_shop_retailer then
    raise exception 'Invitation shop must belong to the same Retailer as the invitation'
      using errcode = 'check_violation';
  end if;

  select r.code
    into v_role_code
  from public.roles r
  where r.id = v_role_id;

  if v_role_code = 'RETAILER_MANAGER' then
    raise exception 'Retailer Manager invitations cannot have shop assignments'
      using errcode = 'check_violation';
  end if;

  -- Only SALES_STAFF may carry shop rows. Belt and braces: the parent role trigger
  -- already restricts an invitation's role to {RETAILER_MANAGER, SALES_STAFF}, so
  -- this rejects anything that is not SALES_STAFF.
  if v_role_code is distinct from 'SALES_STAFF' then
    raise exception 'Invitation shop assignments are permitted only for Sales Staff invitations'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

revoke all     on function public.retailer_invitation_shop_assignments_assert_valid() from public;
revoke execute on function public.retailer_invitation_shop_assignments_assert_valid() from anon;
revoke execute on function public.retailer_invitation_shop_assignments_assert_valid() from authenticated;

create trigger retailer_invitation_shop_assignments_assert_valid_on_insert
  before insert on public.retailer_invitation_shop_assignments
  for each row execute function public.retailer_invitation_shop_assignments_assert_valid();

-- ============================================================================
-- SECTION 11 — Immutable invitation-shop edge
-- ============================================================================
-- A shop row's two FK columns are fixed once inserted. Changing the shop set means
-- revoking the invitation and re-issuing it.
create function public.retailer_invitation_shop_assignments_assert_immutable_edge()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.retailer_staff_invitation_id is distinct from old.retailer_staff_invitation_id
     or new.retailer_shop_id is distinct from old.retailer_shop_id then
    raise exception 'Invitation shop rows are immutable; revoke and re-issue to change them'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

revoke all     on function public.retailer_invitation_shop_assignments_assert_immutable_edge() from public;
revoke execute on function public.retailer_invitation_shop_assignments_assert_immutable_edge() from anon;
revoke execute on function public.retailer_invitation_shop_assignments_assert_immutable_edge() from authenticated;

create trigger retailer_invitation_shop_assignments_assert_immutable_edge_on_update
  before update of retailer_staff_invitation_id, retailer_shop_id
  on public.retailer_invitation_shop_assignments
  for each row
  when (
    new.retailer_staff_invitation_id is distinct from old.retailer_staff_invitation_id
    or new.retailer_shop_id is distinct from old.retailer_shop_id
  )
  execute function public.retailer_invitation_shop_assignments_assert_immutable_edge();

-- ============================================================================
-- SECTION 12 — Shop reverse index (3 total including the PK and the unique index)
-- ============================================================================
-- The unique index leads with retailer_staff_invitation_id and serves apply-on-
-- accept lookups. This reverse index on retailer_shop_id supports shop-dependency
-- lookups and the referencing side of the ON DELETE RESTRICT FK (retiring a shop
-- must scan referencing rows), which the unique index cannot serve.
create index retailer_invitation_shop_assignments_shop_idx
  on public.retailer_invitation_shop_assignments (retailer_shop_id);

-- ============================================================================
-- SECTION 13 — Shop-assignment RLS and privilege hardening
-- ============================================================================
alter table public.retailer_invitation_shop_assignments enable row level security;

revoke all on table public.retailer_invitation_shop_assignments from public;
revoke all on table public.retailer_invitation_shop_assignments from anon;
revoke all on table public.retailer_invitation_shop_assignments from authenticated;

-- ============================================================================
-- SECTION 14 — Internal authorization resolver
-- ============================================================================
-- resolve_retailer_member_organization(target_permission_code text) -> uuid
--
-- Resolves the ONE Retailer organization in which the caller holds
-- target_permission_code through an ACTIVE membership + ACTIVE role, or NULL. This
-- is the authorization ROOT for every future staff RPC: staff actions authorize
-- from the authenticated Retailer member, NOT through the Vendor relationship.
--
-- It mirrors public.resolve_retailer_owner_organization() condition-for-condition
-- with ONE deliberate difference: it does NOT hard-code r.code = 'RETAILER_OWNER'.
-- Instead it admits any ACTIVE role that holds the requested permission, so under
-- the current mappings (migration 20260722210000):
--   * RETAILER_STAFF_MANAGE / _SHOP_ASSIGN are mapped only to RETAILER_OWNER ->
--     resolver(MANAGE|SHOP_ASSIGN) admits ONLY owners.
--   * RETAILER_STAFF_READ is mapped to RETAILER_OWNER and RETAILER_MANAGER ->
--     resolver(READ) admits both; a manager calling a MANAGE-gated RPC resolves
--     NULL and cannot invite.
--
-- DISTINCT organization ids: multiple qualifying roles in ONE retailer collapse to
-- one organization, so "owner who also holds another qualifying role" still
-- resolves that single retailer. The count guard returns the id only when exactly
-- one distinct retailer qualifies, and NULL for zero or two-or-more (fail closed;
-- there is no owner-facing organization switcher yet). No browser-supplied
-- organization id — the caller is auth.uid() and nothing else.
create function public.resolve_retailer_member_organization(
  target_permission_code text
)
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  with qualifying as (
    select distinct o.id
    from public.profiles p
    join public.organization_members m on m.user_id = p.id
    join public.organizations o on o.id = m.organization_id
    join public.member_roles mr on mr.organization_member_id = m.id
    join public.roles r on r.id = mr.role_id
    join public.role_permissions rp on rp.role_id = r.id
    join public.permissions perm on perm.id = rp.permission_id
    where target_permission_code is not null
      and auth.uid() is not null
      and p.id = auth.uid()
      and p.status = 'ACTIVE'
      and m.status = 'ACTIVE'
      and o.status = 'ACTIVE'
      and o.organization_type = 'RETAILER'
      and r.status = 'ACTIVE'
      and perm.code = target_permission_code
  )
  select q.id
  from qualifying q
  where (select count(*) from qualifying) = 1;
$$;

-- Internal only: reachable solely from future SECURITY DEFINER RPCs that run as
-- this function's owner. Not granted to any browser role.
revoke all     on function public.resolve_retailer_member_organization(text) from public;
revoke execute on function public.resolve_retailer_member_organization(text) from anon;
revoke execute on function public.resolve_retailer_member_organization(text) from authenticated;

-- ============================================================================
-- Closing note
-- ============================================================================
-- No existing table, column, constraint, index, trigger, function, role,
-- permission, mapping, or RLS policy was created, altered, or dropped by this
-- migration. public.retailer_invitations, every Retailer Owner invitation and
-- portal function, public.retailer_shop_members, and the roles/permissions
-- catalogue all keep exactly the posture their own migrations left them in. No
-- table privilege is granted to anon or authenticated anywhere here; access to the
-- two new tables exists only through future RPCs.
