/**
 * Unit tests for the browser's pre-flight check, and for its agreement with the server.
 *
 * Run with:  npm test
 *
 * The size threshold is exercised at the exact bytes that matter — one below, exactly
 * at, and one above — because "10 MB" is an inclusive ceiling in this product and an
 * off-by-one here is the difference between accepting and refusing the largest receipt a
 * person is told they may send.
 *
 * Every case is also run through validateReceiptFile, the SERVER's validator, so the two
 * sides cannot start disagreeing about the same file. Where they deliberately differ —
 * the browser never decides a file's type — that difference is asserted too, rather than
 * left to be rediscovered.
 *
 * No network, no Storage, no Supabase client, and no committed fixture: the bytes are
 * generated in memory.
 */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import {
  receiptSelectionRejection,
  type SelectedFileFacts,
} from "./receipt-upload-preflight.ts";
import { validateReceiptFile } from "./receipt-file.ts";
import { MAX_RECEIPT_FILE_BYTES } from "../uploads/upload-policy.ts";

/** A real JPEG signature followed by deterministic filler. Generated, never committed. */
function jpegOfSize(size: number): Uint8Array {
  const bytes = new Uint8Array(size);
  bytes.set([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46]);
  for (let index = 10; index < size; index += 1) bytes[index] = index % 251;
  return bytes;
}

function selection(...sizes: number[]): SelectedFileFacts[] {
  return sizes.map((size) => ({ size }));
}

const ONE_MEGABYTE = 1024 * 1024;

describe("1. the size threshold, at the exact bytes", () => {
  test("1. a small valid image is accepted", () => {
    assert.equal(receiptSelectionRejection(selection(64 * 1024)), null);
  });

  test("2. the size that used to fail at the request boundary is accepted", () => {
    // 1.5 MB: above the Next.js 1 MB Server Action default that produced the original
    // 413, and well below the application maximum. Application policy has never had an
    // opinion against this file — the framework did, and that is now configured.
    const oneAndAHalf = Math.floor(1.5 * ONE_MEGABYTE);
    assert.ok(oneAndAHalf > ONE_MEGABYTE, "the fixture no longer straddles 1 MB");
    assert.equal(receiptSelectionRejection(selection(oneAndAHalf)), null);
  });

  test("3. every size across the 1 MB to 10 MB band is accepted", () => {
    for (let megabytes = 1; megabytes <= 10; megabytes += 1) {
      assert.equal(
        receiptSelectionRejection(selection(megabytes * ONE_MEGABYTE)),
        null,
        `${megabytes} MB was refused by application policy`,
      );
    }
  });

  test("4. one byte below the maximum is accepted", () => {
    assert.equal(receiptSelectionRejection(selection(MAX_RECEIPT_FILE_BYTES - 1)), null);
  });

  test("5. EXACTLY the maximum is accepted — the ceiling is inclusive", () => {
    assert.equal(receiptSelectionRejection(selection(MAX_RECEIPT_FILE_BYTES)), null);
  });

  test("6. one byte above the maximum is refused as too large", () => {
    assert.equal(
      receiptSelectionRejection(selection(MAX_RECEIPT_FILE_BYTES + 1)),
      "too-large",
    );
  });

  test("7. a much larger file is refused the same way", () => {
    assert.equal(
      receiptSelectionRejection(selection(MAX_RECEIPT_FILE_BYTES * 4)),
      "too-large",
    );
  });
});

describe("2. the other things a browser can see for itself", () => {
  test("8. no selection is 'missing'", () => {
    assert.equal(receiptSelectionRejection([]), "missing");
  });

  test("9. a zero-byte selection is 'empty'", () => {
    assert.equal(receiptSelectionRejection(selection(0)), "empty");
  });

  test("10. a nonsensical size is treated as empty, never compared", () => {
    assert.equal(receiptSelectionRejection(selection(-1)), "empty");
    assert.equal(receiptSelectionRejection(selection(Number.NaN)), "empty");
    assert.equal(receiptSelectionRejection(selection(Number.POSITIVE_INFINITY)), "empty");
  });

  test("11. more than one file is refused before anything else is considered", () => {
    // Checked first, matching the server's order, so a selection that is both multiple
    // and over-sized reports the same reason on both sides.
    assert.equal(receiptSelectionRejection(selection(1024, 2048)), "too-many-files");
    assert.equal(
      receiptSelectionRejection(selection(MAX_RECEIPT_FILE_BYTES * 2, 2048)),
      "too-many-files",
    );
  });
});

describe("3. the browser and the server agree about the same file", () => {
  /** The server's verdict for generated bytes of a given size. */
  function serverVerdict(size: number) {
    return validateReceiptFile({
      fileName: "generated-test-receipt.jpg",
      bytes: jpegOfSize(size),
      fileCount: 1,
    });
  }

  test("12. exactly the maximum is accepted by BOTH", () => {
    assert.equal(receiptSelectionRejection(selection(MAX_RECEIPT_FILE_BYTES)), null);
    const verdict = serverVerdict(MAX_RECEIPT_FILE_BYTES);
    assert.equal(verdict.ok, true);
    assert.equal(verdict.ok && verdict.file.sizeBytes, MAX_RECEIPT_FILE_BYTES);
  });

  test("13. one byte above is refused by BOTH, for the same reason", () => {
    assert.equal(
      receiptSelectionRejection(selection(MAX_RECEIPT_FILE_BYTES + 1)),
      "too-large",
    );
    const verdict = serverVerdict(MAX_RECEIPT_FILE_BYTES + 1);
    assert.equal(verdict.ok, false);
    assert.equal(verdict.ok === false && verdict.reason, "too-large");
  });

  test("14. a 1.5 MB image is accepted by BOTH", () => {
    const size = Math.floor(1.5 * ONE_MEGABYTE);
    assert.equal(receiptSelectionRejection(selection(size)), null);
    assert.equal(serverVerdict(size).ok, true);
  });
});

describe("4. signature and type validation are untouched by any of this", () => {
  test("15. the browser deliberately makes NO type decision", () => {
    // A ZIP archive of a legal size passes pre-flight — by design. `File.type` and the
    // picker's `accept` filter are both client-controlled, so refusing on them here
    // would be the browser deciding a file's type, which is exactly what the server
    // refuses to trust. It is sent, and refused there, from its own bytes.
    assert.equal(receiptSelectionRejection(selection(2048)), null);
  });

  test("16. the server still refuses it on its magic bytes", () => {
    const zip = new Uint8Array(2048);
    zip.set([0x50, 0x4b, 0x03, 0x04]);
    const verdict = validateReceiptFile({
      fileName: "not-really-a-receipt.jpg",
      bytes: zip,
      fileCount: 1,
    });
    assert.equal(verdict.ok, false);
    assert.equal(verdict.ok === false && verdict.reason, "unsupported-type");
  });

  test("17. an over-sized file is refused on SIZE before its bytes are examined", () => {
    // Order matters for more than message quality: it is what keeps an over-sized upload
    // from being sniffed and hashed before it is thrown away.
    const oversizedZip = new Uint8Array(MAX_RECEIPT_FILE_BYTES + 1);
    oversizedZip.set([0x50, 0x4b, 0x03, 0x04]);
    const verdict = validateReceiptFile({
      fileName: "big.jpg",
      bytes: oversizedZip,
      fileCount: 1,
    });
    assert.equal(verdict.ok === false && verdict.reason, "too-large");
  });

  test("18. a valid image at the maximum still gets a real SHA-256 and a sniffed type", () => {
    const verdict = validateReceiptFile({
      fileName: "generated-test-receipt.jpg",
      bytes: jpegOfSize(MAX_RECEIPT_FILE_BYTES),
      fileCount: 1,
    });
    assert.equal(verdict.ok, true);
    assert.equal(verdict.ok && verdict.file.mimeType, "image/jpeg");
    assert.match(verdict.ok ? verdict.file.sha256 : "", /^[0-9a-f]{64}$/);
  });
});
